git remote add andportnoy https://github.com/andportnoy/xla
git remote add dimvar https://github.com/dimvar/xla
git remote add inailuig https://github.com/inailuig/xla
git remote add Intel-tensorflow https://github.com/Intel-tensorflow/xla
git remote add jaro-sevcik https://github.com/jaro-sevcik/xla
git remote add jeffhataws https://github.com/jeffhataws/openxla
git remote add jyingl3 https://github.com/jyingl3/xla
git remote add kaixih https://github.com/kaixih/xla
git remote add ManfeiBai https://github.com/ManfeiBai/OpenXLA
git remote add olupton https://github.com/olupton/xla
git remote add openxla https://github.com/openxla/xla
git remote add pearu https://github.com/pearu/xla
git remote add philipphack https://github.com/philipphack/xla
git remote add ROCm https://github.com/ROCm/xla
git remote add shraiysh https://github.com/shraiysh/xla
git remote add Tixxx https://github.com/Tixxx/xla
git remote add trevor-m https://github.com/trevor-m/xla
git remote add wozna https://github.com/wozna/xla
